name: Build
on:
  push:
    branches:
    - master
    - "[0-9]+_[0-9]+_X"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '20' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
        name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'

      - run: npm test
        name: Build

      - run: npm pack
        name: Package
        if: matrix.node == '20'

      - uses: actions/upload-artifact@v4
        if: matrix.node == '20'
        with:
          name: liveview
          path: liveview-*.tgz
