name: Build
on:
  push:
    branches:
    - master
    - "[0-9]+_[0-9]+_X"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
        name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
